name: Docs

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11'

      - name: Cache Julia artifacts
        uses: julia-actions/cache@v2

      - name: Instantiate docs environment
        run: |
          julia --project=docs -e '
            using Pkg;
            Pkg.develop(Pkg.PackageSpec(path=pwd()));
            Pkg.instantiate();
          '

      - name: Build docs
        run: |
          julia --project=docs docs/make.jl

      - name: Deploy docs (gh-pages)
        uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
